// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChungCu.API.Entities;

#nullable disable

namespace QuanLyChungCu.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChungCu.API.Entities.CanHoEntity", b =>
                {
                    b.Property<int>("MaCanHo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCanHo"));

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("MaHoKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCanHo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCanHo");

                    b.ToTable("CanHoTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.HoKhauEntity", b =>
                {
                    b.Property<string>("MaHoKhau")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChiThuongTru")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaHoKhau");

                    b.ToTable("HoKhauTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.KhoanThuEntity", b =>
                {
                    b.Property<int>("MaKhoanThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoanThu"));

                    b.Property<int>("LoaiKhoanThu")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKhoanThu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKhoanThu");

                    b.ToTable("KhoanThuTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.KhoanThuTheoHoEntity", b =>
                {
                    b.Property<int>("MaKhoanThuTheoHo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoanThuTheoHo"));

                    b.Property<string>("MaHoKhau")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaKhoanThu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaKhoanThuTheoHo");

                    b.ToTable("KhoanThuTheoHoTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.NhanKhauEntity", b =>
                {
                    b.Property<int>("MaNhanKhau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanKhau"));

                    b.Property<string>("CanCuocCongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuanHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNhanKhau");

                    b.ToTable("NhanKhauTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.PhanAnhEntity", b =>
                {
                    b.Property<int>("MaPhanAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanAnh"));

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiGui")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiCuaAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhanAnh");

                    b.ToTable("PhanAnhTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.TaiKhoanEntity", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("HoTenHienThi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHoKhau")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoanTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.TamTruEntity", b =>
                {
                    b.Property<int>("MaTamTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTamTru"));

                    b.Property<string>("CanCuocCongDan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChiTamTru")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChiThuongTru")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTamTru");

                    b.ToTable("TamTruTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.TamVangEntity", b =>
                {
                    b.Property<int>("MaTamVang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTamVang"));

                    b.Property<string>("LyDo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaNhanKhau")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiHan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaTamVang");

                    b.HasIndex("MaNhanKhau");

                    b.ToTable("TamVangTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.ThongBaoEntity", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.ToTable("ThongBaoTbl");
                });

            modelBuilder.Entity("QuanLyChungCu.API.Entities.TamVangEntity", b =>
                {
                    b.HasOne("QuanLyChungCu.API.Entities.NhanKhauEntity", "NhanKhau")
                        .WithMany()
                        .HasForeignKey("MaNhanKhau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanKhau");
                });
#pragma warning restore 612, 618
        }
    }
}
